- hosts: localhost
  become: yes
  tasks:
    - name: Update APT package manager
      apt:
        update_cache: yes   
    - name: Installing Redis
      apt:
        name: redis-server 
        state: latest
      notify:
        - restart redis
    - name: Restart Redis Server
      service: 
        name: redis 
        state: restarted
        enabled: yes
