    - name: Install required dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-pymysql